### ISSUE TITLE
State not changing on button presses

### ISSUE THREAD

**Issue by yourAverageDeveloper** [himelbrand/react-native-numeric-input#5] opened 2018-07-25 14:51 UTC
Hey there!
Thanks for the awesome numeric input but there is a problem that i can't solve even by directly copying and pasting your code into mine and running it on my device.
The state or the value of the input is not changing by tapping on either of the '+' and '-' buttons.
Does this happen automatically or do i have to add some kind of functionality behind it myself?

**Comment by himelbrand** [comment] 2018-07-26 08:07
Please add a code sample,
And your environment info: run version and package version
So I can see what the problem is, since the value should change on a click

**Comment by yourAverageDeveloper** [comment] 2018-07-27 10:10
```
import NumericInput from 'react-native-numeric-input'

<NumericInput` 
value={this.state.value}
onChange={(value) => this.setState({value})}
totalWidth={200}
totalHeight={35}
iconSize={25}
step={1}
borderColor='#ffffff'
valueType='integer'
rounded
textColor='#ffffff'
iconStyle={{color: '#586165'}}
rightButtonBackgroundColor='#ffffff'
leftButtonBackgroundColor='#ffffff'
/>
```
I am creating a react native app which has a settings page and this is where i want the users to be able to change the font sizes. The code copied directly from the docs is also not working

**Comment by yourAverageDeveloper** [comment] 2018-07-27 10:15
Okay no, the input IS working but its super dooper slow. The only way i noticed it was when i tapped on the '+' button many times and after a while checked back to see if something had happened.

**Comment by yourAverageDeveloper** [comment] 2018-07-27 10:15
Okay no, the input IS working but its super dooper slow. The only way i noticed it was when i tapped on the '+' button many times and after a while checked back to see if something had happened and the input had been updated. So, yeah it IS changing but is taking a lot of time doing it

**Comment by yourAverageDeveloper** [comment] 2018-07-27 10:18
Okay, i dont know what's happening but the input has started working all of a sudden. All i did was insert a semi-color after an import statement :1st_place_medal:

**Comment by himelbrand** [comment] 2018-07-28 07:46
ok.
so I'm closing the issue.
good luck

**Closed by himelbrand** 2018-07-28 07:46 UTC
