### ISSUE TITLE
react-native-numeric-input "onChange" NOT TRIGGERED

### ISSUE THREAD

**Issue by pavankumarkl** [himelbrand/react-native-numeric-input#35] opened 2019-06-06 10:19 UTC
react-native-numeric-input "onChange" is not getting triggered when value is decremented from 1 to 0

<NumericInput 
                                    value={this.state.cartState[data.id].count} 
                                    onChange={value => this.sendData(data.id,value,rowNumber)}
                                    minValue={0}
                                    iconSize={25}
                                    step={1}
                                    valueType='integer'
                                    rounded={true}
                                    textColor='#B0228C' 
                                    iconStyle={{ color: 'white' }} 
                                    rightButtonBackgroundColor='#EA3788' 
                                    leftButtonBackgroundColor='#E56B70'/>

**Comment by himelbrand** [comment] 2019-06-10 07:57
hi @pavankumarkl 
it will be helpful to see more of your code, for example your state and maybe the function that should be triggered.
in addition please add more info on versions and enviorment so I could help you quicker,
see [here](https://github.com/himelbrand/react-native-numeric-input/blob/master/.github/ISSUE_TEMPLATE/bug_report.md) 
for more info on bug reports.
thanks

**Comment by pavankumarkl** [comment] 2019-06-10 09:35
Thanks a lot for the reply @himelbrand 

**Bug description**: sendData which is a function is usually triggered when there is change in numeric value, but only in the case when value is 1 and then if I decrease it to 0 sendData is not being triggered

onChange={value => this.sendData(data.id,value,rowNumber)} 
sendData(key,value,rowNumber){
       console.log("Inside send data of menu",key,value,this.state.cartState)
        let stateCopy = JSON.parse(JSON.stringify(this.state.cartState))
        stateCopy[key].count = value
        this.setState({
            cartState:stateCopy 
            }) 
        this.props.dispatch(addToCart(this.state.cartState))
    }

### NumericInput component:
<NumericInput 
                                    value={this.state.cartState!= null ?this.state.cartState[data.id].count:0} 
                                    // value={0}
                                    onChange={value => this.sendData(data.id,value,rowNumber)} 
                                    // onLimitReached={(isMax,msg) => console.log(isMax,msg)}
                                    // totalWidth={240} 
                                    // totalHeight={50} 
                                    minValue={0}
                                    iconSize={25}
                                    step={1}
                                    valueType='integer'
                                    rounded={true}
                                    textColor='#B0228C' 
                                    iconStyle={{ color: 'white' }} 
                                    rightButtonBackgroundColor='#EA3788' 
                                    leftButtonBackgroundColor='#E56B70'/>
Case 1:
When I change from 0 to 1 I can see the log, see the attached screen shot.

<img width="1493" alt="Screen Shot 2019-06-10 at 2 57 03 PM" src="https://user-images.githubusercontent.com/18440131/59186516-a9b0d280-8b90-11e9-832d-944d2cc164a2.png">


Case 2: 
When I change from 1 to 0 sendData is not triggered and hence there is no log, see the attached screen shot.

<img width="1493" alt="Screen Shot 2019-06-10 at 2 57 49 PM" src="https://user-images.githubusercontent.com/18440131/59186525-ad445980-8b90-11e9-88d6-2b6876a1a1ea.png">

React Native vesion: 0.59.8
react-native-numeric-input : 6.9.0

**Comment by himelbrand** [comment] 2019-06-10 11:16
@pavankumarkl 
your react-native-numeric-input doesn't make sense, can you please post your package.json?
or the correct version, the newest version is 1.8.0

thank you!

**Comment by pavankumarkl** [comment] 2019-06-20 10:04
@himelbrand 
Sorry posted version of another library, I am using 1.8.0

**Comment by himelbrand** [comment] 2019-07-10 06:53
I believe the issue is resolved when fixed issue #36.
if there is still an issue please open again, closing.
the fix is available on version 1.8.1 on npm.

**Closed by himelbrand** 2019-07-10 06:53 UTC
